apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orchestration-service-pdb
  namespace: cibap-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: orchestration-service
