apiVersion: v1
kind: Service
metadata:
  name: orchestration-service
  namespace: cibap-prod
  labels:
    app: orchestration-service
spec:
  selector:
    app: orchestration-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP
