package com.jpmc.cibap.loan.statemachine;

public enum LoanEvent {

    START_CREDIT_CHECK,
    CREDIT_CHECK_PASSED,
    CREDIT_CHECK_FAILED,
    START_INCOME_VERIFY,
    INCOME_VERIFIED,
    INCOME_UNVERIFIABLE,
    START_RISK_SCORE,
    RISK_SCORE_DONE,
    MAKE_DECISION,
    DECISION_MADE,
    NOTIFY_CUSTOMER,
    NOTIFICATION_SENT
}
