package com.jpmc.cibap.customer.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Persistent entity representing a customer's bank account.
 *
 * <p>Maps directly to the {@code accounts} table managed by Flyway migration
 * {@code V1__create_accounts.sql}. The table is partitioned by {@code customer_id} with
 * a GIN index for hot reads; balances are stored as {@code NUMERIC(18,2)} to avoid
 * floating-point rounding errors.
 *
 * <p><strong>Allowed values:</strong>
 * <ul>
 *   <li>{@code accountType}: {@code CHECKING}, {@code SAVINGS}, {@code CREDIT}</li>
 *   <li>{@code status}: {@code ACTIVE}, {@code FROZEN}, {@code CLOSED}</li>
 * </ul>
 *
 * <p><strong>Optimistic locking:</strong> The {@code @Version} field prevents lost-update
 * anomalies when concurrent reactive pipelines update the same row. R2DBC will throw
 * {@link org.springframework.dao.OptimisticLockingFailureException} on conflict — callers
 * must be prepared to retry.
 *
 * @author Ravi Kafley
 * @since 1.0.0
 */
@Data
@Table("accounts")
public class Account {

    /** Surrogate primary key — UUID generated by {@code gen_random_uuid()} in PostgreSQL. */
    @Id
    private UUID id;

    /**
     * Foreign key to the owning customer record (held in the identity service).
     *
     * <p><strong>⚠ Runtime risk:</strong> If this value is {@code null} at query time,
     * repository queries on {@code customer_id} will silently return no rows rather than
     * throwing. Always validate at the controller layer before propagation.
     */
    private UUID customerId;

    /**
     * Discriminator for account type.
     * Constrained by DB CHECK to: {@code CHECKING}, {@code SAVINGS}, {@code CREDIT}.
     */
    @Column("account_type")
    private String accountType;

    /**
     * Current ledger balance.
     *
     * <p><strong>⚠ Runtime risk:</strong> {@code BigDecimal} arithmetic can throw
     * {@link ArithmeticException} if scale operations are performed without explicit
     * rounding mode. Always use {@link java.math.MathContext} or {@code setScale(2, HALF_UP)}.
     */
    private BigDecimal balance;

    /**
     * Lifecycle status. Constrained by DB CHECK to: {@code ACTIVE}, {@code FROZEN}, {@code CLOSED}.
     * Only {@code ACTIVE} accounts are returned in the public summary API.
     */
    private String status;

    /** Timestamp when the account was created. Managed by the DB ({@code DEFAULT now()}). */
    @Column("created_at")
    private Instant createdAt;

    /**
     * Timestamp of the last update.
     * Triggers a Kafka event on the {@code account-update-events} topic to invalidate the
     * Redis cache for the owning customer.
     */
    @Column("updated_at")
    private Instant updatedAt;

    /**
     * Optimistic-lock version counter.
     * R2DBC increments this on every UPDATE. A stale-read concurrent update will be rejected
     * with {@link org.springframework.dao.OptimisticLockingFailureException}.
     */
    @Version
    private Long version;
}
