apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-runner-egress
  namespace: ctip-execution
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
